/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/articles': {
    /** Returns all recent articles, ranked and paginated */
    get: {
      parameters: {
        query: {
          /** the max number of items returned */
          limit?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': {
              items?: components['schemas']['Article'][];
            };
          };
        };
      };
    };
    /** Insert the given article to the list */
    post: {
      responses: {
        /** CREATED */
        201: {
          content: {
            'application/json': {
              type?: components['schemas']['Article'];
            };
          };
        };
      };
      requestBody: components['requestBodies']['Article'];
    };
  };
  '/article/{articleId}': {
    /** Returns the article with the given id */
    get: {
      parameters: {
        path: {
          articleId: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': {
              type?: components['schemas']['Article'];
            };
          };
        };
      };
    };
    parameters: {
      path: {
        articleId: string;
      };
    };
  };
  '/article/{articleId}/claps': {
    /** Returns the number of claps the user gave to the specified article. */
    get: {
      parameters: {
        path: {
          articleId: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': {
              /** the article claps refer to */
              id: string;
              /** the user making the call */
              caller: string;
              /** The number of claps the user gave to the article, zero if not called yet */
              claps: number;
              /** The last time claps where modified by this user */
              date?: string;
            };
          };
        };
      };
    };
    /** Set the claps from the user for the chosen article. To remove all claps, simply send "claps": 0 */
    put: {
      parameters: {
        path: {
          articleId: string;
        };
      };
      responses: {
        200: components['responses']['PutClaps'];
        201: components['responses']['PutClaps'];
        /** Article not found */
        404: unknown;
      };
      /** The number of claps the user gives to the article */
      requestBody: {
        content: {
          'application/json': {
            claps?: number;
          };
        };
      };
    };
    parameters: {
      path: {
        articleId: string;
      };
    };
  };
}

export interface components {
  schemas: {
    Article: {
      id: string;
      link: string;
      title: string;
      /** who linked the article */
      referrer?: string;
      /** the date in epoch timestamp (millisecond since GMT 1970-01-01) */
      date?: string;
      tags?: string[];
      upvotes: number;
    };
  };
  responses: {
    /** The response to a PUT claps request */
    PutClaps: {
      content: {
        'application/json': {
          caller?: string;
          claps?: number;
        };
      };
    };
  };
  requestBodies: {
    /** A new Article */
    Article: {
      content: {
        'application/json': {
          link: string;
        };
      };
    };
  };
}

export interface operations {}
