/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/articles': {
    /** Returns all recent articles, ranked and paginated */
    get: {
      parameters: {
        query: {
          /** the max number of items returned */
          limit?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': {
              items?: components['schemas']['Article'][];
            };
          };
        };
      };
    };
    /** Insert the given article to the list */
    post: {
      responses: {
        /** CREATED */
        201: {
          content: {
            'application/json': {
              type?: components['schemas']['Article'];
            };
          };
        };
      };
      requestBody: components['requestBodies']['Article'];
    };
  };
  '/article/{articleId}': {
    /** Returns the article with the given id */
    get: {
      parameters: {
        path: {
          articleId: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            'application/json': {
              type?: components['schemas']['Article'];
            };
          };
        };
      };
    };
    parameters: {
      path: {
        articleId: string;
      };
    };
  };
}

export interface components {
  schemas: {
    Article: {
      id: string;
      link: string;
      title: string;
      /** who linked the article */
      referrer?: string;
      /** the date in epoch timestamp (millisecond since GMT 1970-01-01) */
      date?: string;
      tags?: string[];
      upvotes: number;
    };
  };
  requestBodies: {
    /** A new Article */
    Article: {
      content: {
        'application/json': {
          link: string;
        };
      };
    };
  };
}

export interface operations {}
