name: Infrastructure Build

on:
  pull_request:
    paths:
      - 'infrastructure/**/*'
  push:
    branches:
      - 'main'
    paths:
      - 'infrastructure/**/*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: infrastructure/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('infrastructure/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install, Test, Build
        run: |
          cd infrastructure
          npm install
          npm run lint
          npm run build
